### ISSUE TITLE
Flatpak: Permissions are unable to mount USB or network drives

### ISSUE THREAD

**Issue by hunttom** [cryptomator/flathub#1]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Flatpak permissions do not allow use of USB/Network drives

### What software is involved?

- Operating System: PopOS 22.04
- Cryptomator: 1.6.15

### Volume Type

FUSE

### Steps to Reproduce

1. Install 1.5.16 using Flatpak.
2. Mount USB drive or network drive
3. Open Cryptomator and either try to create or mount a Vault in a network or USB drive. 
5. Cryptomator will not be able to see/use drive.

### Expected Behavior

Cryptomator is able to use network or USB drives.

### Actual Behavior

Flatpak permissions do not allow for use of network drives or USB devices. 

### Reproducibility

Always

### Relevant Log Output

```shell
N/A
```

### Anything else?

Confirmed that AppImage has appropriate permissions and was able to grant permissions using Flatseal to all drives.

**Comment by infeo** [comment]
This is a deliberate decision with the idea to restrict the app access as much as possible and force the user to willingly upgrade it on demand.

Of course, it can be discussed that there are a lot of users accessing vaults from somewhere else than the home dir.
____
The line determining what can be accessed on the host : https://github.com/flathub/org.cryptomator.Cryptomator/blob/887e62f780d739f0d42d643e7718443c964db472/org.cryptomator.Cryptomator.yaml#L12

**Comment by hunttom** [comment]
Thanks @infeo! Understood and I appreciate that clarification. 

My confusion came from the idea that Cryptomator was a transparent data encryption wherever you kept your data. Seeing the cloud drives on the home page, I assumed that it would naturally support those services like the Windows, Mac, and mobile applications. Ideally, I would like to have a consistent experience when using Cryptomator across Windows, Mac, Linux, Android, and iOS - though I understand that I have very little insight into the decisions made by the development team.

Feel free to either close or we can discuss further in adding the clarity to the Flatpak documentation that the application will not natively support cloud nor external drives.

Warmly,
u_d

**Comment by SailReal** [comment]
While flatpak.org writes

> **Sandboxed applications:** one of Flatpak’s main goals is to increase the security of desktop systems by isolating applications from one another. This is achieved using sandboxing and means that, by default, applications that are run with Flatpak have limited access to the host environment.

the topic is definitely debatable but we discussed it while pushing Cryptomator into Flatpak/Flathub, as result we changed `filesystem` from `host` to `home` in https://github.com/flathub/org.cryptomator.Cryptomator/commit/088bd0be775c9da1cd00c82976fbff0dd5f87e7e# since our guess is that the vast majority of vaults are located in home. These people benefit from not having directly given full permission to anything.

If a user wants to give permission to a different path, simply override this permission using e.g.

```
$ sudo flatpak override org.cryptomator.Cryptomator --filesystem=/media/hdd1
```
or they can set it to `host`, but this is then a decision by the user and not the default for all users by the maintainers.

There are also GUI tools like Flatseal to customize the permissions of Fatpak packages for people that don't like a terminal.

On the one hand this seems to be a restriction, on the other hand we have such restrictions in other places too, e.g. if a user wants to access a mounted vault with root privileges or using another Linux user, this is not possible directly, specific mount flags must be provided in the Cryptomator app for the same reason as here, the vast majority are protected by this "feature", those that need it can change it.

What we have to do in any case is to document it so that users know why it is like this, how to change it, as a basis we can take https://community.cryptomator.org/t/cryptomator-flatpak-doesnt-find-safes/9613/2?u=sailreal. Is already longer on our list to write it^^.

> Feel free to either close or we can discuss further in adding the clarity to the Flatpak documentation that the application will not natively support cloud nor external drives.

A constructive discussion, like this one, is always welcome!

Regardless of what we set `filesystem` to, the question is where the user puts the synchronized folder of the cloud or the mount point of the external drive to, or in general, where the vault folder is located. So it is not true to say that Cryptomator do not natively support cloud or external drives using Flatpak, it depends on the path in connection with what was set in `filesystem`. In my case, my Nextcloud is synchronized to `/home/julian/cloud` which would perfectly fit into `filesystem=home`. But as mentioned in the beginning, it is debatable what permission by default is required to use Cryptomator which results in which paths should be supported by default with one of the main purposes of Flatpak in mind: The isolation of applications by restricting permissions as much as possible.

How do you see that @hunttom?

**Comment by hunttom** [comment]
Nah, you've been right far and considerate when it comes to security.

My only concern is that I thought the Flatpak was broken because I couldn't find the documentation. Is it possible to add your comment to the Flatpak documentation to ensure folks like myself understand how to enable - I seriously thought that Cryptomator on Linux wasn't working.

Anyway, closing this bug/feature. Thanks for explaining it!
